### PR TITLE
Feat/rest api

### PR DESCRIPTION
**Pull request by Aatishsharma77**
## what

Feature

- Add Rest API and Private Rest API
- Add Cloudwatch log group and KMS keys.

Fixes

- Payload version in HTTP API

### CODE REVIEW

**Comment by h1manshu98** [comment]
Please update the description with all the changes you have made in this PR

**Review by h1manshu98 — APPROVED** [review]
LGTM!

**Review by themaniskshah — APPROVED** [review]

**Review by h1manshu98 — APPROVED** [review]
LGTM!

**Review by omsharma07 — APPROVED** [review]
LGTM

**Review by vaibhav7797 — APPROVED** [review]
LGTM!

**Pull request merged**
